Repository capstone-waa/client, pull requests merged in 2023-06, with the labels that each got.

#31 [FEATURE] myPage 관련 작업
  App.js
  accordion-collapse-react-native.d.ts
  package-lock.json
  package.json
  src/components/Layout.js
  src/pages/LoginPage.js
  src/pages/MyPage.js
  src/utils/validationSize.js
Labels: 예림, FEATURE, Design

#32 🐛🎨 로그인/회원가입 반응형
  src/components/MyButton.js
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
  src/pages/STTS.js
Labels: CHORE, 정훈, Design

#28 ✨ 위험 의심 페이지 / 키워드 페이지 생성
  App.js
  package-lock.json
  package.json
  src/components/GamePhone.js
  src/components/GameTablet.js
  src/components/Stats/Chip.js
  src/components/Stats/Danger.js
  src/components/Stats/Frequent.js
  src/pages/CounselingPage.js
  src/pages/StatsPage.js
  src/pages/TwentyQuestionPage.js
  src/pages/WordChainLandingPage.js
  src/pages/WordChainPage.js
  src/recoil/atoms/commonAtom.js
Labels: 채연, Design
